### ISSUE TITLE
Action deve ser recurso no servidor que consiga processar os dados enviados

### ISSUE THREAD

**Issue by carlosbazilio** [felipeCarnevale/trabalhoProgWeb#2]
https://github.com/felipeCarnevale/trabalhoProgWeb/blob/98bd4700d25a34c16da73b317ddc7ab4cc2d9773/login.html#L27

**Comment by felipeCarnevale** [comment]
Nós deixamos assim pois não temos nada da parte do servidor feita ainda, estávamos só começando a dar forma pras telas de login e registro.
