### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by carlosbazilio** [felipeCarnevale/trabalhoProgWeb#4]
Estilos comuns deveriam estar num único local. Isso acontece, por exemplo, com o background-color. Desta forma, deveria ter um arquivo .css para o que é comum no projeto, e estilos internos contendo o que é específico ou deve ser sobrescrever as definições mais gerais.

https://github.com/felipeCarnevale/trabalhoProgWeb/blob/7a7db410642c6e33c661131db8cb34190e30bca1/login.html#L21

O Daniel Henry ainda não contribuiu com o projeto, certo !? Peça a ele para fazer esta mudança, blz !?

**Comment by GummyTheProgrammy** [comment]
Olá Bazilio, Felipe já me mandou algumas vezes o email sobre me tornar contribuidor, eu clico em "view invite" ele me redireciona pro início do repositório apenas, nenhuma notificação chego pelo site do github pra mim, só por email.
Por enquanto posso ficar contribuindo pelo Pull Request?

**Comment by carlosbazilio** [comment]
Sim
